"use client"

import Head from "next/head";
import { useEffect, useState } from "react";
import { authorize, getToken } from "../api/authorize";
import Player from "@/components/Player";

export default function Home() {
  const [codeVerifier, setCodeVerifier] = useState("");

  useEffect(() => {
    setCodeVerifier(sessionStorage.getItem("code_verifier") || "");
  }, []);

  const authorizeApp = async () => {
    await authorize();
  };

  useEffect(() => {
    getToken();
  }, [codeVerifier]);

  return (
    <>
      <Head>
        <title>Spotify 2.0</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {codeVerifier ? (
          <>
            <div>
              <button onClick={authorizeApp} className="btn btn-accent">
                Refresh Token
              </button>
            </div>
            <Player />
          </>
        ) : (
          <button onClick={authorizeApp} className="btn btn-accent">
            Authorize
          </button>
        )}
      </main>
    </>
  );
}